version: '3.7'

networks:
  traefik:
    name: traefik

services:
  traefik:
    container_name: traefik
#    build:
#      context: ./
    image: traefik:2.1
#    isolation: process
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
#      - 8080:8080 # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/etc/traefik:ro
      - ./certs:/etc/certs:ro
    labels:
      - traefik.enable=true

      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik.local`)
      - traefik.http.routers.traefik.middlewares=https-redirect@file

      - traefik.http.routers.traefik-ssl.entrypoints=https
      - traefik.http.routers.traefik-ssl.rule=Host(`traefik.local`)
      - traefik.http.routers.traefik-ssl.service=api@internal
      - traefik.http.routers.traefik-ssl.tls=true
      - traefik.http.routers.traefik-ssl.middlewares=default-whitelist@file